Main svc
Almor47/java-explore-with-me pull request #7
Opened 2023-08-18 11:35 UTC by Almor47

2023-08-19 10:20 UTC, sergeymamonov requested changes
В качестве улучшения классы dto можно сделать иммутабельными.

Проверку пуст ли массив можно делать не через .size() == 0,  а с помощью .isEmpty().

2023-08-19 10:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/event/dto/EventMapper.java
> +    @Mapping(target = "publishedOn", expression = "java(null)")
Я бы вместо expression = "java(null)" лучше бы выбрал ignore = true

2023-08-19 10:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/event/dto/RequestMapper.java
> +    @Mapping(target = "event", expression = "java(request.getEvent().getId())")
Не нужно через "java(... делать . Мапстрак сам подтянет поле, поэтому пишете expression = request.event.id

2023-08-19 10:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/event/repository/EventCriteriaRepository.java
> +    List<Event> getEventsPublic(String text, List<Long> categories, Boolean paid, LocalDateTime rangeStart,
Если в метод нужно передать много параметров, то лучше сделать объект, в который положить все эти параметры. И тогда в метод нужно будет передать только один этот объект. Плюс если добавится еще один параметр, который нужно будет передать в метод, то нужно будет добавить поле в класс. Сигнатура метода при этом не изменится.

2023-08-19 10:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/handler/ApiError.java
> +    //private String errors;
В проекте не должно быть закомментированных строчек кода

2023-08-19 10:20 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/handler/ErrorHandler.java
> +        //stringWriter.toString();
В проекте не должно быть закомментированных строчек кода

2023-08-19 11:17 UTC, Almor47 commented on main-service/src/main/java/ru/practicum/main_service/event/dto/RequestMapper.java
> +    @Mapping(target = "event", expression = "java(request.getEvent().getId())")
Здравствуйте, хотел бы уточнить expression = request.event.id если написать так, вместо expression = "java(request.getEvent().getId())" то ошибка при сборке проекта 
event has private access in ru.practicum.main_service.event.model.Request, если добавить гетерры expression = request.gerEvent().getId(), то при сборке 
expression not allowed as annotation value

2023-08-20 20:12 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/event/dto/RequestMapper.java
> +    @Mapping(target = "event", expression = "java(request.getEvent().getId())")
извиняюсь, описался выше не expression нужно использовать, а source. 

@Mapping(target = "event", source = request.event.id).

Да, аннотация @Getter (явно или включенной в другую аннотацию) должна быть, чтобы Mapstruct использовал геттеры.

А, expression ожидает, что будет передаваться какое-то выражение, поэтому как вы делали работает, а с явным путем уже не работает. Но лучше явный путь указывать в source.

2023-08-20 20:14 UTC, sergeymamonov approved these changes

2023-08-20 20:14 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/main_service/event/repository/EventCriteriaRepository.java
> +    List<Event> getEventsPublic(ParametersForPublicSearch parametersForPublicSearch);
Часто используют слово Query, самостоятельно или с другими словами для названия таких классов.

2023-08-20 20:14 UTC, sergeymamonov commented on stats-service/stats-server/src/main/java/ru/practicum/stats_server/handler/ApiError.java
> +    //private String errors;
Закомментированный код.

2023-08-21 16:03 UTC, Almor47 commented on main-service/src/main/java/ru/practicum/main_service/event/dto/RequestMapper.java
> +    @Mapping(target = "event", expression = "java(request.getEvent().getId())")
![image](https://github.com/Almor47/java-explore-with-me/assets/92159365/61f15028-8e07-4557-ad62-0119bbc4b438)

2023-08-22 12:19 UTC, merged